from __future__ import annotations

from datetime import datetime, timezone

from .pipeline import RunResult
from .timeline import render_timeline

DRAFT_BANNER = (
    "> **DRAFT — pending human review.** Generated by rca-generator; "
    "verify each section, resolve flagged gaps, then `rca-generator publish`."
)

# Section order is the output contract from SPEC.md — identical every run.
_SECTION_ORDER = ("executive_summary", "problem_statement", "timeline", "root_cause", "action_items")


def render_draft(run: RunResult) -> str:
    parts = [f"# RCA: {run.incident}", "", DRAFT_BANNER, ""]
    for name in _SECTION_ORDER:
        result = run.section(name)
        parts += [f"## {result.stage.title}", ""]
        parts += [gap for gap in result.gaps]
        if result.gaps:
            parts.append("")
        parts += [result.text, ""]
        if name == "timeline":
            parts += ["### Merged events", "", render_timeline(run.events), ""]

    parts += ["## Data Gaps", ""]
    if run.gaps:
        parts += [f"- {gap}" for gap in run.gaps]
    else:
        parts.append("- None detected: all evidence sources were available.")

    parts += ["", "## Appendix: Token Usage", "", run.ledger.render()]
    parts += ["", "## Appendix: Agent Trace", "", _render_trace(run)]

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts += ["", f"_Generated {generated}._"]
    return "\n".join(parts)


def _render_trace(run: RunResult) -> str:
    """Per-stage record of which fetch tools the agent called and turns taken."""
    lines = ["| Stage | Turns | Tools called |", "|---|---|---|"]
    for result in run.results:
        tools = ", ".join(result.tools_called) if result.tools_called else "—"
        lines.append(f"| {result.stage.name} | {result.turns} | {tools} |")
    return "\n".join(lines)
